"""initial schema

Revision: 0001
Revises: None
Created: 2026-10-01

Hand-written, never autogenerated (review decision D4): autogenerate cannot
express vector(384), the HNSW index, the generated tsvector column or the
partial indexes. The SQL is a frozen copy of docs/design/schema.sql at the
time of this migration, kept beside it so later edits to the design document
can never change what migration 0001 does. Its BEGIN and COMMIT lines are
dropped because Alembic owns the transaction.

Index decision: every index is listed with its query in docs/design/data-model.md.
"""

from collections.abc import Sequence
from pathlib import Path

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SQL = Path(__file__).with_name("0001_initial_schema.sql")
TABLES = ("llm_calls", "reminders", "obligations", "extractions", "clauses", "contracts")
TYPES = (
    "reminder_status",
    "obligation_kind",
    "review_reason",
    "extraction_status",
    "extraction_field",
    "contract_type",
)


def statements(sql: str) -> list[str]:
    """Split the file into single statements; asyncpg runs one per call.

    A statement ends with `;` at the end of a line. Comment text may contain
    `; ` mid-line, so splitting on every semicolon would cut it in two.
    """
    body = "\n".join(line for line in sql.splitlines() if not line.startswith("--"))
    parts = [part.strip() for part in body.split(";\n")]
    return [p.rstrip(";") for p in parts if p and p.rstrip(";") not in ("BEGIN", "COMMIT")]


def upgrade() -> None:
    """Create the extension, enum types, tables, comments and indexes."""
    for statement in statements(SQL.read_text()):
        op.execute(statement)


def downgrade() -> None:
    """Drop everything upgrade created, children first."""
    for table in TABLES:
        op.execute(f"DROP TABLE {table}")
    for enum in TYPES:
        op.execute(f"DROP TYPE {enum}")
    op.execute("DROP EXTENSION vector")
