"""initial schema

Migration: 0001_initial_schema                 Task: TASK-001
Store: postgres (pgvector/pgvector:pg16)       Phase: expand (1 of 1: new database, no old shape)
Purpose: create the pgvector extension, 6 enum types and the 6 tables of
  docs/design/schema.sql (contracts, clauses, extractions, obligations,
  reminders, llm_calls) with their comments, checks and indexes.
Locks: none that matter: every table is new and empty.
Rows: 0 at creation; about 10^3 per table in this project (data-model.md section 4).
Index: every index and the query it serves is listed in docs/design/data-model.md.
Retention / PII: retention UNDEFINED (data-model.md section 6); reminders.recipient is
  personal data (contact), stored in plain text, synthetic project only.
Down: drops all 6 tables, the 6 enum types and the vector extension;
  Down loses: all data; tested in: make migrate-verify (CI integration job).

Hand-written, never autogenerated (review decision D4): autogenerate cannot
express vector(384), the HNSW index, the generated tsvector column or the
partial indexes. The SQL is a frozen copy of docs/design/schema.sql at the
time of this migration, kept beside it so later edits to the design document
can never change what migration 0001 does. Its BEGIN and COMMIT lines are
dropped because Alembic owns the transaction. Statements run through
exec_driver_sql, so SQLAlchemy never parses them for bind parameters (the
CHECK regexes contain "[:space:]").

This migration owns the vector extension: it creates it and its Down drops it.
Revision id "0001_initial_schema", not "0001": the scaffold's probe migration
used "0001", and a database migrated on main must not mistake this one for it.
"""

from collections.abc import Sequence
from pathlib import Path

from alembic import op

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SQL = Path(__file__).with_name("0001_initial_schema.sql")
TABLES = ("llm_calls", "reminders", "obligations", "extractions", "clauses", "contracts")
TYPES = (
    "reminder_status",
    "obligation_kind",
    "review_reason",
    "extraction_status",
    "extraction_field",
    "contract_type",
)


def statements(sql: str) -> list[str]:
    """Split the file into single statements; asyncpg runs one per call.

    A statement ends with `;` at the end of a line. Comment text may contain
    `; ` mid-line, so splitting on every semicolon would cut it in two.
    """
    body = "\n".join(line for line in sql.splitlines() if not line.startswith("--"))
    parts = [part.strip() for part in body.split(";\n")]
    return [p.rstrip(";") for p in parts if p and p.rstrip(";") not in ("BEGIN", "COMMIT")]


def upgrade() -> None:
    """Create the extension, enum types, tables, comments and indexes."""
    connection = op.get_bind()
    for statement in statements(SQL.read_text()):
        connection.exec_driver_sql(statement)


def downgrade() -> None:
    """Drop everything upgrade created, children first."""
    for table in TABLES:
        op.execute(f"DROP TABLE {table}")
    for enum in TYPES:
        op.execute(f"DROP TYPE {enum}")
    op.execute("DROP EXTENSION vector")
